services:
  mysql:
    image: mysql:8.4
    container_name: jobportal-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: voanhhao2606
      MYSQL_DATABASE: jobportal_topcv
      MYSQL_USER: haovo
      MYSQL_PASSWORD: jobportal_2606
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7-alpine
    container_name: jobportal-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: jobportal-opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Haovo@12345
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

volumes:
  mysql-data:
  redis-data:
  opensearch-data: