export type VietnamDistrict = {
  name: string;
  aliases?: string[];
};

export type VietnamProvince = {
  code: string;
  name: string;
  aliases: string[];
  districts: VietnamDistrict[];
};

const d = (name: string, aliases?: string[]): VietnamDistrict =>
  aliases ? { name, aliases } : { name };

/** 34 tỉnh thành sau sắp xếp 2025, kèm quận huyện còn dùng trên địa chỉ tuyển dụng. */
export const VIETNAM_LOCATIONS: VietnamProvince[] = [
  {
    code: "HN",
    name: "Thành phố Hà Nội",
    aliases: ["ha noi", "hanoi"],
    districts: [
      d("Quận Ba Đình"),
      d("Quận Hoàn Kiếm"),
      d("Quận Tây Hồ"),
      d("Quận Long Biên"),
      d("Quận Cầu Giấy"),
      d("Quận Đống Đa"),
      d("Quận Hai Bà Trưng"),
      d("Quận Hoàng Mai"),
      d("Quận Thanh Xuân"),
      d("Quận Nam Từ Liêm", ["nam tu liem"]),
      d("Quận Bắc Từ Liêm", ["bac tu liem"]),
      d("Quận Hà Đông"),
      d("Thị xã Sơn Tây"),
      d("Huyện Ba Vì"),
      d("Huyện Chương Mỹ"),
      d("Huyện Đan Phượng"),
      d("Huyện Đông Anh"),
      d("Huyện Gia Lâm"),
      d("Huyện Hoài Đức"),
      d("Huyện Mê Linh"),
      d("Huyện Mỹ Đức"),
      d("Huyện Phú Xuyên"),
      d("Huyện Phúc Thọ"),
      d("Huyện Quốc Oai"),
      d("Huyện Sóc Sơn"),
      d("Huyện Thạch Thất"),
      d("Huyện Thanh Oai"),
      d("Huyện Thanh Trì"),
      d("Huyện Thường Tín"),
      d("Huyện Ứng Hòa"),
    ],
  },
  {
    code: "HUE",
    name: "Thành phố Huế",
    aliases: ["hue", "thua thien hue"],
    districts: [
      d("Quận Thuận Hóa"),
      d("Quận Phú Xuân"),
      d("Thị xã Hương Thủy"),
      d("Thị xã Hương Trà"),
      d("Huyện Phong Điền"),
      d("Huyện Quảng Điền"),
      d("Huyện Phú Vang"),
      d("Huyện Phú Lộc"),
      d("Huyện A Lưới"),
    ],
  },
  {
    code: "LC",
    name: "Lai Châu",
    aliases: ["lai chau"],
    districts: [d("Thành phố Lai Châu"), d("Huyện Tam Đường"), d("Huyện Phong Thổ"), d("Huyện Sìn Hồ")],
  },
  {
    code: "DB",
    name: "Điện Biên",
    aliases: ["dien bien"],
    districts: [d("Thành phố Điện Biên Phủ"), d("Thị xã Mường Lay"), d("Huyện Điện Biên"), d("Huyện Mường Chà")],
  },
  {
    code: "SL",
    name: "Sơn La",
    aliases: ["son la"],
    districts: [d("Thành phố Sơn La"), d("Huyện Mộc Châu"), d("Huyện Mai Sơn"), d("Huyện Yên Châu")],
  },
  {
    code: "LS",
    name: "Lạng Sơn",
    aliases: ["lang son"],
    districts: [d("Thành phố Lạng Sơn"), d("Huyện Cao Lộc"), d("Huyện Văn Lãng"), d("Huyện Chi Lăng")],
  },
  {
    code: "QN",
    name: "Quảng Ninh",
    aliases: ["quang ninh"],
    districts: [
      d("Thành phố Hạ Long"),
      d("Thành phố Cẩm Phả"),
      d("Thành phố Uông Bí"),
      d("Thành phố Móng Cái"),
      d("Thị xã Đông Triều"),
      d("Thị xã Quảng Yên"),
      d("Huyện Vân Đồn"),
    ],
  },
  {
    code: "TH",
    name: "Thanh Hóa",
    aliases: ["thanh hoa"],
    districts: [
      d("Thành phố Thanh Hóa"),
      d("Thành phố Sầm Sơn"),
      d("Thị xã Bỉm Sơn"),
      d("Thị xã Nghi Sơn"),
      d("Huyện Đông Sơn"),
      d("Huyện Quảng Xương"),
    ],
  },
  {
    code: "NA",
    name: "Nghệ An",
    aliases: ["nghe an"],
    districts: [
      d("Thành phố Vinh"),
      d("Thị xã Cửa Lò"),
      d("Thị xã Thái Hòa"),
      d("Thị xã Hoàng Mai"),
      d("Huyện Nghi Lộc"),
      d("Huyện Diễn Châu"),
    ],
  },
  {
    code: "HT",
    name: "Hà Tĩnh",
    aliases: ["ha tinh"],
    districts: [d("Thành phố Hà Tĩnh"), d("Thị xã Hồng Lĩnh"), d("Thị xã Kỳ Anh"), d("Huyện Cẩm Xuyên")],
  },
  {
    code: "CB",
    name: "Cao Bằng",
    aliases: ["cao bang"],
    districts: [d("Thành phố Cao Bằng"), d("Huyện Hòa An"), d("Huyện Quảng Hòa"), d("Huyện Trùng Khánh")],
  },
  {
    code: "TQ",
    name: "Tuyên Quang",
    aliases: ["tuyen quang", "ha giang"],
    districts: [
      d("Thành phố Tuyên Quang"),
      d("Thành phố Hà Giang"),
      d("Huyện Yên Sơn"),
      d("Huyện Sơn Dương"),
      d("Huyện Đồng Văn"),
    ],
  },
  {
    code: "LCA",
    name: "Lào Cai",
    aliases: ["lao cai", "yen bai"],
    districts: [
      d("Thành phố Lào Cai"),
      d("Thành phố Yên Bái"),
      d("Thị xã Sa Pa"),
      d("Thị xã Nghĩa Lộ"),
      d("Huyện Bảo Thắng"),
    ],
  },
  {
    code: "TN",
    name: "Thái Nguyên",
    aliases: ["thai nguyen", "bac kan"],
    districts: [
      d("Thành phố Thái Nguyên"),
      d("Thành phố Sông Công"),
      d("Thành phố Bắc Kạn"),
      d("Thị xã Phổ Yên"),
      d("Huyện Đồng Hỷ"),
    ],
  },
  {
    code: "PT",
    name: "Phú Thọ",
    aliases: ["phu tho", "vinh phuc", "hoa binh", "vinh yen"],
    districts: [
      d("Thành phố Việt Trì"),
      d("Thành phố Vĩnh Yên"),
      d("Thành phố Phúc Yên"),
      d("Thành phố Hòa Bình"),
      d("Thị xã Phú Thọ"),
      d("Huyện Lâm Thao"),
    ],
  },
  {
    code: "BN",
    name: "Bắc Ninh",
    aliases: ["bac ninh", "bac giang"],
    districts: [
      d("Thành phố Bắc Ninh"),
      d("Thành phố Bắc Giang"),
      d("Thành phố Từ Sơn"),
      d("Huyện Yên Phong"),
      d("Huyện Quế Võ"),
      d("Huyện Thuận Thành"),
    ],
  },
  {
    code: "HY",
    name: "Hưng Yên",
    aliases: ["hung yen", "thai binh"],
    districts: [
      d("Thành phố Hưng Yên"),
      d("Thành phố Thái Bình"),
      d("Thị xã Mỹ Hào"),
      d("Huyện Văn Lâm"),
      d("Huyện Văn Giang"),
      d("Huyện Khoái Châu"),
    ],
  },
  {
    code: "HP",
    name: "Thành phố Hải Phòng",
    aliases: ["hai phong", "hai duong"],
    districts: [
      d("Quận Hồng Bàng"),
      d("Quận Ngô Quyền"),
      d("Quận Lê Chân"),
      d("Quận Hải An"),
      d("Quận Kiến An"),
      d("Quận Đồ Sơn"),
      d("Quận Dương Kinh"),
      d("Huyện An Dương"),
      d("Huyện Thủy Nguyên"),
      d("Thành phố Hải Dương"),
      d("Thành phố Chí Linh"),
    ],
  },
  {
    code: "NB",
    name: "Ninh Bình",
    aliases: ["ninh binh", "nam dinh", "ha nam"],
    districts: [
      d("Thành phố Ninh Bình"),
      d("Thành phố Tam Điệp"),
      d("Thành phố Nam Định"),
      d("Thành phố Phủ Lý"),
      d("Huyện Hoa Lư"),
      d("Huyện Gia Viễn"),
    ],
  },
  {
    code: "QT",
    name: "Quảng Trị",
    aliases: ["quang tri", "quang binh", "dong hoi", "dong ha"],
    districts: [
      d("Thành phố Đông Hà"),
      d("Thị xã Quảng Trị"),
      d("Thành phố Đồng Hới"),
      d("Thị xã Ba Đồn"),
      d("Huyện Gio Linh"),
    ],
  },
  {
    code: "DN",
    name: "Thành phố Đà Nẵng",
    aliases: ["da nang", "quang nam", "hoi an", "tam ky"],
    districts: [
      d("Quận Hải Châu"),
      d("Quận Thanh Khê"),
      d("Quận Sơn Trà"),
      d("Quận Ngũ Hành Sơn"),
      d("Quận Liên Chiểu"),
      d("Quận Cẩm Lệ"),
      d("Huyện Hòa Vang"),
      d("Thành phố Hội An"),
      d("Thành phố Tam Kỳ"),
    ],
  },
  {
    code: "QNG",
    name: "Quảng Ngãi",
    aliases: ["quang ngai", "kon tum"],
    districts: [
      d("Thành phố Quảng Ngãi"),
      d("Thị xã Đức Phổ"),
      d("Thành phố Kon Tum"),
      d("Huyện Sơn Tịnh"),
      d("Huyện Bình Sơn"),
    ],
  },
  {
    code: "GL",
    name: "Gia Lai",
    aliases: ["gia lai", "binh dinh", "quy nhon"],
    districts: [
      d("Thành phố Pleiku"),
      d("Thị xã An Khê"),
      d("Thị xã Ayun Pa"),
      d("Thành phố Quy Nhơn"),
      d("Thị xã An Nhơn"),
      d("Huyện Chư Păh"),
    ],
  },
  {
    code: "KH",
    name: "Khánh Hòa",
    aliases: ["khanh hoa", "nha trang", "ninh thuan", "phan rang"],
    districts: [
      d("Thành phố Nha Trang"),
      d("Thành phố Cam Ranh"),
      d("Thị xã Ninh Hòa"),
      d("Thành phố Phan Rang - Tháp Chàm"),
      d("Huyện Diên Khánh"),
    ],
  },
  {
    code: "LD",
    name: "Lâm Đồng",
    aliases: ["lam dong", "da lat", "bao loc", "dak nong", "binh thuan", "phan thiet"],
    districts: [
      d("Thành phố Đà Lạt"),
      d("Thành phố Bảo Lộc"),
      d("Thành phố Gia Nghĩa"),
      d("Thành phố Phan Thiết"),
      d("Thị xã La Gi"),
      d("Huyện Đức Trọng"),
    ],
  },
  {
    code: "DL",
    name: "Đắk Lắk",
    aliases: ["dak lak", "daklak", "buon ma thuot", "phu yen", "tuy hoa"],
    districts: [
      d("Thành phố Buôn Ma Thuột"),
      d("Thị xã Buôn Hồ"),
      d("Thành phố Tuy Hòa"),
      d("Thị xã Sông Cầu"),
      d("Huyện Cư M'gar"),
    ],
  },
  {
    code: "HCM",
    name: "Thành phố Hồ Chí Minh",
    aliases: ["ho chi minh", "sai gon", "hcm", "tphcm", "binh duong", "ba ria", "vung tau"],
    districts: [
      d("Quận 1", ["q1", "quan 1"]),
      d("Quận 3", ["q3", "quan 3"]),
      d("Quận 4", ["q4", "quan 4"]),
      d("Quận 5", ["q5", "quan 5"]),
      d("Quận 6", ["q6", "quan 6"]),
      d("Quận 7", ["q7", "quan 7"]),
      d("Quận 8", ["q8", "quan 8"]),
      d("Quận 10", ["q10", "quan 10"]),
      d("Quận 11", ["q11", "quan 11"]),
      d("Quận 12", ["q12", "quan 12"]),
      d("Quận Bình Thạnh"),
      d("Quận Bình Tân"),
      d("Quận Gò Vấp"),
      d("Quận Phú Nhuận"),
      d("Quận Tân Bình"),
      d("Quận Tân Phú"),
      d("Thành phố Thủ Đức", ["quan 2", "q2", "quan 9", "q9", "thao dien"]),
      d("Huyện Bình Chánh"),
      d("Huyện Cần Giờ"),
      d("Huyện Củ Chi"),
      d("Huyện Hóc Môn"),
      d("Huyện Nhà Bè"),
      d("Thành phố Thủ Dầu Một"),
      d("Thành phố Dĩ An"),
      d("Thành phố Thuận An"),
      d("Thành phố Bến Cát"),
      d("Thành phố Bà Rịa"),
      d("Thành phố Vũng Tàu"),
    ],
  },
  {
    code: "DNA",
    name: "Đồng Nai",
    aliases: ["dong nai", "bien hoa", "binh phuoc", "dong xoai"],
    districts: [
      d("Thành phố Biên Hòa"),
      d("Thành phố Long Khánh"),
      d("Huyện Nhơn Trạch"),
      d("Huyện Trảng Bom"),
      d("Huyện Long Thành"),
      d("Thành phố Đồng Xoài"),
    ],
  },
  {
    code: "TNI",
    name: "Tây Ninh",
    aliases: ["tay ninh", "long an", "tan an", "duc hoa"],
    districts: [
      d("Thành phố Tây Ninh"),
      d("Thị xã Hòa Thành"),
      d("Thị xã Trảng Bàng"),
      d("Thành phố Tân An"),
      d("Huyện Đức Hòa"),
      d("Huyện Bến Lức"),
    ],
  },
  {
    code: "CT",
    name: "Thành phố Cần Thơ",
    aliases: ["can tho", "soc trang", "hau giang"],
    districts: [
      d("Quận Ninh Kiều"),
      d("Quận Bình Thủy"),
      d("Quận Cái Răng"),
      d("Quận Ô Môn"),
      d("Quận Thốt Nốt"),
      d("Thành phố Sóc Trăng"),
      d("Thành phố Vị Thanh"),
    ],
  },
  {
    code: "VL",
    name: "Vĩnh Long",
    aliases: ["vinh long", "ben tre", "tra vinh"],
    districts: [
      d("Thành phố Vĩnh Long"),
      d("Thị xã Bình Minh"),
      d("Thành phố Bến Tre"),
      d("Thành phố Trà Vinh"),
      d("Huyện Long Hồ"),
    ],
  },
  {
    code: "DT",
    name: "Đồng Tháp",
    aliases: ["dong thap", "cao lanh", "sa dec", "tien giang", "my tho"],
    districts: [
      d("Thành phố Cao Lãnh"),
      d("Thành phố Sa Đéc"),
      d("Thành phố Hồng Ngự"),
      d("Thành phố Mỹ Tho"),
      d("Thị xã Gò Công"),
      d("Huyện Cao Lãnh"),
    ],
  },
  {
    code: "CM",
    name: "Cà Mau",
    aliases: ["ca mau", "bac lieu"],
    districts: [
      d("Thành phố Cà Mau"),
      d("Huyện Năm Căn"),
      d("Huyện Ngọc Hiển"),
      d("Thành phố Bạc Liêu"),
      d("Huyện Hòa Bình"),
    ],
  },
  {
    code: "AG",
    name: "An Giang",
    aliases: ["an giang", "long xuyen", "chau doc", "kien giang", "rach gia", "phu quoc"],
    districts: [
      d("Thành phố Long Xuyên"),
      d("Thành phố Châu Đốc"),
      d("Thị xã Tân Châu"),
      d("Thành phố Rạch Giá"),
      d("Thành phố Hà Tiên"),
      d("Thành phố Phú Quốc"),
    ],
  },
];
