/**
 * Quyền mà route `/admin` thực sự kiểm tra (`requirePermission`).
 * Tên trong DB seed cũ dạng `MODULE_ACTION` (vd. `USER_APPROVE`) không khớp các chuỗi này.
 */
export const ADMIN_ROUTE_PERMISSIONS: {
  name: string;
  module: string;
  action: string;
}[] = [
  { name: "admin:dashboard:read", module: "DASHBOARD", action: "VIEW" },
  { name: "admin:users:read", module: "USER", action: "VIEW" },
  { name: "admin:users:create", module: "USER", action: "CREATE" },
  { name: "admin:users:update", module: "USER", action: "UPDATE" },
  { name: "admin:users:delete", module: "USER", action: "DELETE" },
  { name: "admin:companies:read", module: "COMPANY", action: "VIEW" },
  { name: "admin:companies:create", module: "COMPANY", action: "CREATE" },
  { name: "admin:companies:update", module: "COMPANY", action: "UPDATE" },
  { name: "admin:companies:delete", module: "COMPANY", action: "DELETE" },
  { name: "admin:moderation:read", module: "MODERATION", action: "VIEW" },
  { name: "admin:moderation:approve", module: "MODERATION", action: "APPROVE" },
  { name: "admin:moderation:reject", module: "MODERATION", action: "REJECT" },
  { name: "admin:categories:read", module: "CATEGORY", action: "VIEW" },
  { name: "admin:categories:create", module: "CATEGORY", action: "CREATE" },
  { name: "admin:categories:update", module: "CATEGORY", action: "UPDATE" },
  { name: "admin:categories:delete", module: "CATEGORY", action: "DELETE" },
  { name: "admin:jobs:read", module: "JOB", action: "VIEW" },
  { name: "admin:jobs:create", module: "JOB", action: "CREATE" },
  { name: "admin:jobs:update", module: "JOB", action: "UPDATE" },
  { name: "admin:jobs:delete", module: "JOB", action: "DELETE" },
  { name: "admin:jobs:approve", module: "JOB", action: "APPROVE" },
  { name: "admin:jobs:reject", module: "JOB", action: "REJECT" },
  { name: "admin:jobs:feature", module: "JOB", action: "FEATURE" },
  { name: "admin:settings:read", module: "SETTING", action: "VIEW" },
  { name: "admin:settings:update", module: "SETTING", action: "UPDATE" },
  { name: "admin:locations:read", module: "LOCATION", action: "VIEW" },
  { name: "admin:locations:create", module: "LOCATION", action: "CREATE" },
  { name: "admin:locations:update", module: "LOCATION", action: "UPDATE" },
  { name: "admin:locations:delete", module: "LOCATION", action: "DELETE" },
  { name: "admin:skills:read", module: "SKILL", action: "VIEW" },
  { name: "admin:skills:create", module: "SKILL", action: "CREATE" },
  { name: "admin:skills:update", module: "SKILL", action: "UPDATE" },
  { name: "admin:skills:delete", module: "SKILL", action: "DELETE" },
  { name: "admin:resumes:read", module: "RESUME", action: "VIEW" },
  { name: "admin:resumes:create", module: "RESUME", action: "CREATE" },
  { name: "admin:resumes:update", module: "RESUME", action: "UPDATE" },
  { name: "admin:resumes:delete", module: "RESUME", action: "DELETE" },
  { name: "admin:applications:read", module: "APPLICATION", action: "VIEW" },
  { name: "admin:applications:update", module: "APPLICATION", action: "UPDATE" },
  { name: "admin:cv_templates:read", module: "CV_TEMPLATE", action: "VIEW" },
  { name: "admin:cv_templates:create", module: "CV_TEMPLATE", action: "CREATE" },
  { name: "admin:cv_templates:update", module: "CV_TEMPLATE", action: "UPDATE" },
  { name: "admin:cv_templates:delete", module: "CV_TEMPLATE", action: "DELETE" },
  { name: "admin:audit_logs:read", module: "AUDIT_LOG", action: "VIEW" },
  { name: "admin:access_control:read", module: "ACCESS_CONTROL", action: "VIEW" },
  { name: "admin:access_control:create", module: "ACCESS_CONTROL", action: "CREATE" },
  { name: "admin:access_control:update", module: "ACCESS_CONTROL", action: "UPDATE" },
  { name: "admin:access_control:delete", module: "ACCESS_CONTROL", action: "DELETE" },
  { name: "admin:blog:read", module: "BLOG", action: "VIEW" },
  { name: "admin:blog:create", module: "BLOG", action: "CREATE" },
  { name: "admin:blog:update", module: "BLOG", action: "UPDATE" },
  { name: "admin:blog:delete", module: "BLOG", action: "DELETE" },
  { name: "admin:contact:read", module: "CONTACT", action: "VIEW" },
];
